FROM node:lts

WORKDIR /app/frontend

# Copie les fichiers nécessaires
COPY frontend/package.json frontend/package-lock.json ./

RUN yarn install

# Copie le reste du code
COPY frontend .

EXPOSE 3000
